[package]
name = "reapixa"
version = "0.1.0"
edition = "2021"

[dependencies]
rouille = { version = "3.5", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
maud = "0.23"
ureq = { version = "2.4", features = ["json", "tls", "rustls"] }
percent-encoding = "2.1"
rustls = "0.20"
rustls-native-certs = "0.6"
lazy_static = "1.4"
chrono = { version = "0.4.19", default-features = false, features = ["clock"] }

[build-dependencies]
grass = "0.10.8"
glob = "0.3.0"
